### ISSUE TITLE
Support version

### ISSUE THREAD

**Issue by weileiming** [alexiscn/WXNavigationBar#1]
Hi,
The iOS version supported by most App is below iOS 12. Can you degrade the supported version of WXNavigationBar?

**Comment by alexiscn** [comment]
Maybe iOS 11 cloud be supported. I will
check it out.

**Comment by alexiscn** [comment]
> Hi,
> The iOS version supported by most App is below iOS 12. Can you degrade the supported version of WXNavigationBar?

iOS 11.0 is supported now.

**Comment by weileiming** [comment]
> > Hi,
> > The iOS version supported by most App is below iOS 12. Can you degrade the supported version of WXNavigationBar?
> 
> iOS 11.0 is supported now.

Thanks,maye iOS 9 or iOS 10.What do you think?

**Comment by alexiscn** [comment]
`WXNavigationBar` now support iOS 9.0 + since version `2.0.0`.

If there is any adaptation problem, feel free to open an issue. :D
