### ISSUE TITLE
pod 2.3.6 失败

### ISSUE THREAD

**Issue by LAnqxpp** [alexiscn/WXNavigationBar#10]

**Comment by alexiscn** [comment]
make sure your pod file looks like following code:

```sh
pod 'WXNavigationBar', '~> 2.3.6'
```

then try `pod repo update` or `pod install --repo-update`.

**Comment by alexiscn** [comment]
Do you fix the problem ?

**Comment by LAnqxpp** [comment]
platform :ios, '9.0'
这样就好
