### ISSUE TITLE
导航栏透明的时候无法点击

### ISSUE THREAD

**Issue by ccchitat** [alexiscn/WXNavigationBar#11]

**Comment by alexiscn** [comment]
Please describe your problem more clearly.

You mean 

- The button under the transparent navigation can not be clicked ?
- The button inside the wx_navigation bar can note be clicked ?
- The navigation item can not be clicked when the navigation bar is transparent ?

The more detail your describes, the easier it is to solve.

**Comment by ccchitat** [comment]
The button under the transparent navigation can not be clicked

**Comment by alexiscn** [comment]
> The button under the transparent navigation can not be clicked

You can add button to `wx_navigationbar` to enable touch.

**Comment by ccchitat** [comment]
I just give an example, in fact, I need the view to be able to receive events

**Comment by iOSyan** [comment]
> I just give an example, in fact, I need the view to be able to receive events

请问这个问题解决了吗？遇到同样的问题，导航栏隐藏或透明时，在导航栏位置的view无法相应点击事件

**Comment by alexiscn** [comment]
You can hide navigation bar in `viewWillAppear(_ animated: Bool)` and show in `viewWillDisappear(_ animated: Bool)`

```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
```
