### ISSUE TITLE
在使用本库时候，同时使用ZLPhotoBrowser导航栏白色了

### ISSUE THREAD

**Issue by df13954** [alexiscn/WXNavigationBar#15]
https://github.com/longitachi/ZLPhotoBrowser
引入最新版本这个图片选择库，在选择图片的时候，最顶部的导航栏默认显示取消，和切换文件夹的。
现在和本库一起使用，顶部的导航栏变了灰白色，且无法点击了~
环境：xcode 12.4，iPhone 11，ios13.6

**Comment by alexiscn** [comment]
/// Enable WXNavigationBar on UINavigationController, `true` by default.
    /// You can use this property to specify special navigationController to not use WXNavigationBar.
    /// eg:
    /// let rootViewController = RootViewController()
    /// let rootNav = FLNavigationController(rootViewController: rootViewController)
    /// rootNav.wx_enableWXNavigationBar = false
    /// present(rootNav, animated: true)
