### ISSUE TITLE
对UIViewController的扩展属性希望能通过点语法修改，而不只是重写属性

### ISSUE THREAD

**Issue by lzzhoujielun** [alexiscn/WXNavigationBar#3]
问题：如果使用第三方框架提供的控制器需要到控制器类部重写属性，需要改源码
期望：提供属性set的方式，通过点语法修改（目前是只读）
效果：viewController.wx_useSystemBlurNavBar = true

**Comment by alexiscn** [comment]
You can override `wx_useSystemBlurNavBar` in extension.

```swift
extension TDViewController {
    override var wx_useSystemBlurNavBar: Bool {
        return true
    }
}
```

**Comment by lzzhoujielun** [comment]
Forget can also be extended, thanks for providing ideas！
