### ISSUE TITLE
有没有设置状态栏前景色的方法或者属性呢

### ISSUE THREAD

**Issue by chinghoi** [alexiscn/WXNavigationBar#4]
我的页面结构里用到了 UITabBarController， UInavigaionController， 设置这个非常的麻烦，希望能提供这个方法用来设置它，感谢库作者

**Comment by alexiscn** [comment]
You can try `wx_titleTextAttributes`. 

```swift
override var wx_titleTextAttributes: [NSAttributedString.Key: Any]? {
    return [.foregroundColor: UIColor.red]
}
```

**Comment by chinghoi** [comment]
可能我没有表述清楚，是 statusBarStyle的属性，请问下有没有修改这个的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"alexiscn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月26日(星期五) 晚上8:42
收件人:&nbsp;"alexiscn/WXNavigationBar"<WXNavigationBar@noreply.github.com&gt;;
抄送:&nbsp;"chinghoi"<56465334@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alexiscn/WXNavigationBar] 有没有设置状态栏前景色的方法或者属性呢 (#4)





 
You can try wx_titleTextAttributes.
 override var wx_titleTextAttributes: [NSAttributedString.Key: Any]? {     return [.foregroundColor: UIColor.red] }

**Comment by alexiscn** [comment]
Using `preferredStatusBarStyle` not working? 
Can you provide a demo and what effect do you want.
