### ISSUE TITLE
隐藏状态栏之后，导航栏上移

### ISSUE THREAD

**Issue by jhchenchong** [alexiscn/WXNavigationBar#5]

**Comment by alexiscn** [comment]
I will fix it in next version.

**Comment by alexiscn** [comment]
It seems a bug of iOS, and I can not found a solution of that.  :(

I create a simplest project which contains following item:

- UINavigationController
- ViewControllerA (rootViewController of navigationController)
- ViewControllerB ( A push to B. B set `preferredStatusBarHidden` to `true` )

By adding following code to ViewControllerA may fix the movement of view. But it is so ugly.

```swift
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        // Force layout subviews
        let layoutContainerView = navigationController?.navigationBar.superview
        layoutContainerView?.setNeedsLayout()
        layoutContainerView?.layoutIfNeeded()
    }
```

I do not recommend you to hide status bar in a navigation stack(which will cause the inconsistency of layouts). 
You can hide status bar in present view controller.

**Comment by jhchenchong** [comment]
thx
