### ISSUE TITLE
自定义burttonItem加载网络图片时，点击进入其它页面时尺寸就会有问题

### ISSUE THREAD

**Issue by luowen1991** [alexiscn/WXNavigationBar#7]
let avatarImageView = UIImageView(frame: .init(x: 0, y: 0, width: 40, height: 40))
        avatarImageView.layer.cornerRadius = 20
        avatarImageView.layer.masksToBounds = true
        avatarImageView.kf.setImage(with: URL(string: "http://i0.hdslb.com/bfs/archive/689ed56f5b8b9bd26a90b20c52d464ebc0156185.png"))

        let leftButtonItem = UIBarButtonItem(customView: avatarImageView)

**Comment by alexiscn** [comment]
I will check it when I have time.
